# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Filters-LazyLoader
version:      0.05
version_from: lib/Template/Filters/LazyLoader.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Module::Recursive::Require:    0.04
    Template:                      0
    Test::Differences:             0
    Test::Exception:               0
    UNIVERSAL::require:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
